/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppOutreachIndexRouteImport } from './routes/_app.outreach.index'
import { Route as AppPointsStrategyRouteImport } from './routes/_app.points.strategy'
import { Route as AppAuthUserRouteImport } from './routes/_app.auth.user'
import { Route as AppAuthAdminRouteImport } from './routes/_app.auth.admin'
import { Route as AppAuthAdminIndexRouteImport } from './routes/_app.auth.admin.index'
import { Route as AppAuthUserUsersRouteImport } from './routes/_app.auth.user.users'
import { Route as AppAuthUserLoginSimRouteImport } from './routes/_app.auth.user.login-sim'
import { Route as AppAuthUserEnterpriseRouteImport } from './routes/_app.auth.user.enterprise'
import { Route as AppAuthAdminUsersRouteImport } from './routes/_app.auth.admin.users'
import { Route as AppAuthAdminTenantsRouteImport } from './routes/_app.auth.admin.tenants'
import { Route as AppAuthAdminLevelsRouteImport } from './routes/_app.auth.admin.levels'
import { Route as AppAuthAdminAuditRouteImport } from './routes/_app.auth.admin.audit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachIndexRoute = AppOutreachIndexRouteImport.update({
  id: '/outreach/',
  path: '/outreach/',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsStrategyRoute = AppPointsStrategyRouteImport.update({
  id: '/points/strategy',
  path: '/points/strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthUserRoute = AppAuthUserRouteImport.update({
  id: '/auth/user',
  path: '/auth/user',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthAdminRoute = AppAuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthAdminIndexRoute = AppAuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthAdminRoute,
} as any)
const AppAuthUserUsersRoute = AppAuthUserUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAuthUserRoute,
} as any)
const AppAuthUserLoginSimRoute = AppAuthUserLoginSimRouteImport.update({
  id: '/login-sim',
  path: '/login-sim',
  getParentRoute: () => AppAuthUserRoute,
} as any)
const AppAuthUserEnterpriseRoute = AppAuthUserEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => AppAuthUserRoute,
} as any)
const AppAuthAdminUsersRoute = AppAuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAuthAdminRoute,
} as any)
const AppAuthAdminTenantsRoute = AppAuthAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppAuthAdminRoute,
} as any)
const AppAuthAdminLevelsRoute = AppAuthAdminLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AppAuthAdminRoute,
} as any)
const AppAuthAdminAuditRoute = AppAuthAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/admin': typeof AppAuthAdminRouteWithChildren
  '/auth/user': typeof AppAuthUserRouteWithChildren
  '/points/strategy': typeof AppPointsStrategyRoute
  '/outreach/': typeof AppOutreachIndexRoute
  '/auth/admin/audit': typeof AppAuthAdminAuditRoute
  '/auth/admin/levels': typeof AppAuthAdminLevelsRoute
  '/auth/admin/tenants': typeof AppAuthAdminTenantsRoute
  '/auth/admin/users': typeof AppAuthAdminUsersRoute
  '/auth/user/enterprise': typeof AppAuthUserEnterpriseRoute
  '/auth/user/login-sim': typeof AppAuthUserLoginSimRoute
  '/auth/user/users': typeof AppAuthUserUsersRoute
  '/auth/admin/': typeof AppAuthAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth/user': typeof AppAuthUserRouteWithChildren
  '/points/strategy': typeof AppPointsStrategyRoute
  '/outreach': typeof AppOutreachIndexRoute
  '/auth/admin/audit': typeof AppAuthAdminAuditRoute
  '/auth/admin/levels': typeof AppAuthAdminLevelsRoute
  '/auth/admin/tenants': typeof AppAuthAdminTenantsRoute
  '/auth/admin/users': typeof AppAuthAdminUsersRoute
  '/auth/user/enterprise': typeof AppAuthUserEnterpriseRoute
  '/auth/user/login-sim': typeof AppAuthUserLoginSimRoute
  '/auth/user/users': typeof AppAuthUserUsersRoute
  '/auth/admin': typeof AppAuthAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/auth/admin': typeof AppAuthAdminRouteWithChildren
  '/_app/auth/user': typeof AppAuthUserRouteWithChildren
  '/_app/points/strategy': typeof AppPointsStrategyRoute
  '/_app/outreach/': typeof AppOutreachIndexRoute
  '/_app/auth/admin/audit': typeof AppAuthAdminAuditRoute
  '/_app/auth/admin/levels': typeof AppAuthAdminLevelsRoute
  '/_app/auth/admin/tenants': typeof AppAuthAdminTenantsRoute
  '/_app/auth/admin/users': typeof AppAuthAdminUsersRoute
  '/_app/auth/user/enterprise': typeof AppAuthUserEnterpriseRoute
  '/_app/auth/user/login-sim': typeof AppAuthUserLoginSimRoute
  '/_app/auth/user/users': typeof AppAuthUserUsersRoute
  '/_app/auth/admin/': typeof AppAuthAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/admin'
    | '/auth/user'
    | '/points/strategy'
    | '/outreach/'
    | '/auth/admin/audit'
    | '/auth/admin/levels'
    | '/auth/admin/tenants'
    | '/auth/admin/users'
    | '/auth/user/enterprise'
    | '/auth/user/login-sim'
    | '/auth/user/users'
    | '/auth/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/user'
    | '/points/strategy'
    | '/outreach'
    | '/auth/admin/audit'
    | '/auth/admin/levels'
    | '/auth/admin/tenants'
    | '/auth/admin/users'
    | '/auth/user/enterprise'
    | '/auth/user/login-sim'
    | '/auth/user/users'
    | '/auth/admin'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/auth/admin'
    | '/_app/auth/user'
    | '/_app/points/strategy'
    | '/_app/outreach/'
    | '/_app/auth/admin/audit'
    | '/_app/auth/admin/levels'
    | '/_app/auth/admin/tenants'
    | '/_app/auth/admin/users'
    | '/_app/auth/user/enterprise'
    | '/_app/auth/user/login-sim'
    | '/_app/auth/user/users'
    | '/_app/auth/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/': {
      id: '/_app/outreach/'
      path: '/outreach'
      fullPath: '/outreach/'
      preLoaderRoute: typeof AppOutreachIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/strategy': {
      id: '/_app/points/strategy'
      path: '/points/strategy'
      fullPath: '/points/strategy'
      preLoaderRoute: typeof AppPointsStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/user': {
      id: '/_app/auth/user'
      path: '/auth/user'
      fullPath: '/auth/user'
      preLoaderRoute: typeof AppAuthUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/admin': {
      id: '/_app/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AppAuthAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/admin/': {
      id: '/_app/auth/admin/'
      path: '/'
      fullPath: '/auth/admin/'
      preLoaderRoute: typeof AppAuthAdminIndexRouteImport
      parentRoute: typeof AppAuthAdminRoute
    }
    '/_app/auth/user/users': {
      id: '/_app/auth/user/users'
      path: '/users'
      fullPath: '/auth/user/users'
      preLoaderRoute: typeof AppAuthUserUsersRouteImport
      parentRoute: typeof AppAuthUserRoute
    }
    '/_app/auth/user/login-sim': {
      id: '/_app/auth/user/login-sim'
      path: '/login-sim'
      fullPath: '/auth/user/login-sim'
      preLoaderRoute: typeof AppAuthUserLoginSimRouteImport
      parentRoute: typeof AppAuthUserRoute
    }
    '/_app/auth/user/enterprise': {
      id: '/_app/auth/user/enterprise'
      path: '/enterprise'
      fullPath: '/auth/user/enterprise'
      preLoaderRoute: typeof AppAuthUserEnterpriseRouteImport
      parentRoute: typeof AppAuthUserRoute
    }
    '/_app/auth/admin/users': {
      id: '/_app/auth/admin/users'
      path: '/users'
      fullPath: '/auth/admin/users'
      preLoaderRoute: typeof AppAuthAdminUsersRouteImport
      parentRoute: typeof AppAuthAdminRoute
    }
    '/_app/auth/admin/tenants': {
      id: '/_app/auth/admin/tenants'
      path: '/tenants'
      fullPath: '/auth/admin/tenants'
      preLoaderRoute: typeof AppAuthAdminTenantsRouteImport
      parentRoute: typeof AppAuthAdminRoute
    }
    '/_app/auth/admin/levels': {
      id: '/_app/auth/admin/levels'
      path: '/levels'
      fullPath: '/auth/admin/levels'
      preLoaderRoute: typeof AppAuthAdminLevelsRouteImport
      parentRoute: typeof AppAuthAdminRoute
    }
    '/_app/auth/admin/audit': {
      id: '/_app/auth/admin/audit'
      path: '/audit'
      fullPath: '/auth/admin/audit'
      preLoaderRoute: typeof AppAuthAdminAuditRouteImport
      parentRoute: typeof AppAuthAdminRoute
    }
  }
}

interface AppAuthAdminRouteChildren {
  AppAuthAdminAuditRoute: typeof AppAuthAdminAuditRoute
  AppAuthAdminLevelsRoute: typeof AppAuthAdminLevelsRoute
  AppAuthAdminTenantsRoute: typeof AppAuthAdminTenantsRoute
  AppAuthAdminUsersRoute: typeof AppAuthAdminUsersRoute
  AppAuthAdminIndexRoute: typeof AppAuthAdminIndexRoute
}

const AppAuthAdminRouteChildren: AppAuthAdminRouteChildren = {
  AppAuthAdminAuditRoute: AppAuthAdminAuditRoute,
  AppAuthAdminLevelsRoute: AppAuthAdminLevelsRoute,
  AppAuthAdminTenantsRoute: AppAuthAdminTenantsRoute,
  AppAuthAdminUsersRoute: AppAuthAdminUsersRoute,
  AppAuthAdminIndexRoute: AppAuthAdminIndexRoute,
}

const AppAuthAdminRouteWithChildren = AppAuthAdminRoute._addFileChildren(
  AppAuthAdminRouteChildren,
)

interface AppAuthUserRouteChildren {
  AppAuthUserEnterpriseRoute: typeof AppAuthUserEnterpriseRoute
  AppAuthUserLoginSimRoute: typeof AppAuthUserLoginSimRoute
  AppAuthUserUsersRoute: typeof AppAuthUserUsersRoute
}

const AppAuthUserRouteChildren: AppAuthUserRouteChildren = {
  AppAuthUserEnterpriseRoute: AppAuthUserEnterpriseRoute,
  AppAuthUserLoginSimRoute: AppAuthUserLoginSimRoute,
  AppAuthUserUsersRoute: AppAuthUserUsersRoute,
}

const AppAuthUserRouteWithChildren = AppAuthUserRoute._addFileChildren(
  AppAuthUserRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAuthAdminRoute: typeof AppAuthAdminRouteWithChildren
  AppAuthUserRoute: typeof AppAuthUserRouteWithChildren
  AppPointsStrategyRoute: typeof AppPointsStrategyRoute
  AppOutreachIndexRoute: typeof AppOutreachIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAuthAdminRoute: AppAuthAdminRouteWithChildren,
  AppAuthUserRoute: AppAuthUserRouteWithChildren,
  AppPointsStrategyRoute: AppPointsStrategyRoute,
  AppOutreachIndexRoute: AppOutreachIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
