/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppOutreachIndexRouteImport } from './routes/_app.outreach.index'
import { Route as AppPointsTransactionsRouteImport } from './routes/_app.points.transactions'
import { Route as AppPointsTenantsRouteImport } from './routes/_app.points.tenants'
import { Route as AppPointsAppsRouteImport } from './routes/_app.points.apps'
import { Route as AppAuthUserRouteImport } from './routes/_app.auth.user'
import { Route as AppPointsTransactionsIndexRouteImport } from './routes/_app.points.transactions.index'
import { Route as AppPointsTransactionsPointsLedgerRouteImport } from './routes/_app.points.transactions.points-ledger'
import { Route as AppPointsProductsRechargeRouteImport } from './routes/_app.points.products.recharge'
import { Route as AppPointsProductsCategoriesRouteImport } from './routes/_app.points.products.categories'
import { Route as AppPointsProductsBundlesRouteImport } from './routes/_app.points.products.bundles'
import { Route as AppPointsProductsBasicRouteImport } from './routes/_app.points.products.basic'
import { Route as AppAuthUserUsersRouteImport } from './routes/_app.auth.user.users'
import { Route as AppAuthUserLoginSimRouteImport } from './routes/_app.auth.user.login-sim'
import { Route as AppPointsTransactionsRechargeIndexRouteImport } from './routes/_app.points.transactions.recharge.index'
import { Route as AppPointsTransactionsRechargeNewRouteImport } from './routes/_app.points.transactions.recharge.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachIndexRoute = AppOutreachIndexRouteImport.update({
  id: '/outreach/',
  path: '/outreach/',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsTransactionsRoute = AppPointsTransactionsRouteImport.update({
  id: '/points/transactions',
  path: '/points/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsTenantsRoute = AppPointsTenantsRouteImport.update({
  id: '/points/tenants',
  path: '/points/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsAppsRoute = AppPointsAppsRouteImport.update({
  id: '/points/apps',
  path: '/points/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthUserRoute = AppAuthUserRouteImport.update({
  id: '/auth/user',
  path: '/auth/user',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsTransactionsIndexRoute =
  AppPointsTransactionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPointsTransactionsRoute,
  } as any)
const AppPointsTransactionsPointsLedgerRoute =
  AppPointsTransactionsPointsLedgerRouteImport.update({
    id: '/points-ledger',
    path: '/points-ledger',
    getParentRoute: () => AppPointsTransactionsRoute,
  } as any)
const AppPointsProductsRechargeRoute =
  AppPointsProductsRechargeRouteImport.update({
    id: '/points/products/recharge',
    path: '/points/products/recharge',
    getParentRoute: () => AppRoute,
  } as any)
const AppPointsProductsCategoriesRoute =
  AppPointsProductsCategoriesRouteImport.update({
    id: '/points/products/categories',
    path: '/points/products/categories',
    getParentRoute: () => AppRoute,
  } as any)
const AppPointsProductsBundlesRoute =
  AppPointsProductsBundlesRouteImport.update({
    id: '/points/products/bundles',
    path: '/points/products/bundles',
    getParentRoute: () => AppRoute,
  } as any)
const AppPointsProductsBasicRoute = AppPointsProductsBasicRouteImport.update({
  id: '/points/products/basic',
  path: '/points/products/basic',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthUserUsersRoute = AppAuthUserUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAuthUserRoute,
} as any)
const AppAuthUserLoginSimRoute = AppAuthUserLoginSimRouteImport.update({
  id: '/login-sim',
  path: '/login-sim',
  getParentRoute: () => AppAuthUserRoute,
} as any)
const AppPointsTransactionsRechargeIndexRoute =
  AppPointsTransactionsRechargeIndexRouteImport.update({
    id: '/recharge/',
    path: '/recharge/',
    getParentRoute: () => AppPointsTransactionsRoute,
  } as any)
const AppPointsTransactionsRechargeNewRoute =
  AppPointsTransactionsRechargeNewRouteImport.update({
    id: '/recharge/new',
    path: '/recharge/new',
    getParentRoute: () => AppPointsTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/user': typeof AppAuthUserRouteWithChildren
  '/points/apps': typeof AppPointsAppsRoute
  '/points/tenants': typeof AppPointsTenantsRoute
  '/points/transactions': typeof AppPointsTransactionsRouteWithChildren
  '/outreach/': typeof AppOutreachIndexRoute
  '/auth/user/login-sim': typeof AppAuthUserLoginSimRoute
  '/auth/user/users': typeof AppAuthUserUsersRoute
  '/points/products/basic': typeof AppPointsProductsBasicRoute
  '/points/products/bundles': typeof AppPointsProductsBundlesRoute
  '/points/products/categories': typeof AppPointsProductsCategoriesRoute
  '/points/products/recharge': typeof AppPointsProductsRechargeRoute
  '/points/transactions/points-ledger': typeof AppPointsTransactionsPointsLedgerRoute
  '/points/transactions/': typeof AppPointsTransactionsIndexRoute
  '/points/transactions/recharge/new': typeof AppPointsTransactionsRechargeNewRoute
  '/points/transactions/recharge/': typeof AppPointsTransactionsRechargeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth/user': typeof AppAuthUserRouteWithChildren
  '/points/apps': typeof AppPointsAppsRoute
  '/points/tenants': typeof AppPointsTenantsRoute
  '/outreach': typeof AppOutreachIndexRoute
  '/auth/user/login-sim': typeof AppAuthUserLoginSimRoute
  '/auth/user/users': typeof AppAuthUserUsersRoute
  '/points/products/basic': typeof AppPointsProductsBasicRoute
  '/points/products/bundles': typeof AppPointsProductsBundlesRoute
  '/points/products/categories': typeof AppPointsProductsCategoriesRoute
  '/points/products/recharge': typeof AppPointsProductsRechargeRoute
  '/points/transactions/points-ledger': typeof AppPointsTransactionsPointsLedgerRoute
  '/points/transactions': typeof AppPointsTransactionsIndexRoute
  '/points/transactions/recharge/new': typeof AppPointsTransactionsRechargeNewRoute
  '/points/transactions/recharge': typeof AppPointsTransactionsRechargeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/auth/user': typeof AppAuthUserRouteWithChildren
  '/_app/points/apps': typeof AppPointsAppsRoute
  '/_app/points/tenants': typeof AppPointsTenantsRoute
  '/_app/points/transactions': typeof AppPointsTransactionsRouteWithChildren
  '/_app/outreach/': typeof AppOutreachIndexRoute
  '/_app/auth/user/login-sim': typeof AppAuthUserLoginSimRoute
  '/_app/auth/user/users': typeof AppAuthUserUsersRoute
  '/_app/points/products/basic': typeof AppPointsProductsBasicRoute
  '/_app/points/products/bundles': typeof AppPointsProductsBundlesRoute
  '/_app/points/products/categories': typeof AppPointsProductsCategoriesRoute
  '/_app/points/products/recharge': typeof AppPointsProductsRechargeRoute
  '/_app/points/transactions/points-ledger': typeof AppPointsTransactionsPointsLedgerRoute
  '/_app/points/transactions/': typeof AppPointsTransactionsIndexRoute
  '/_app/points/transactions/recharge/new': typeof AppPointsTransactionsRechargeNewRoute
  '/_app/points/transactions/recharge/': typeof AppPointsTransactionsRechargeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/user'
    | '/points/apps'
    | '/points/tenants'
    | '/points/transactions'
    | '/outreach/'
    | '/auth/user/login-sim'
    | '/auth/user/users'
    | '/points/products/basic'
    | '/points/products/bundles'
    | '/points/products/categories'
    | '/points/products/recharge'
    | '/points/transactions/points-ledger'
    | '/points/transactions/'
    | '/points/transactions/recharge/new'
    | '/points/transactions/recharge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/user'
    | '/points/apps'
    | '/points/tenants'
    | '/outreach'
    | '/auth/user/login-sim'
    | '/auth/user/users'
    | '/points/products/basic'
    | '/points/products/bundles'
    | '/points/products/categories'
    | '/points/products/recharge'
    | '/points/transactions/points-ledger'
    | '/points/transactions'
    | '/points/transactions/recharge/new'
    | '/points/transactions/recharge'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/auth/user'
    | '/_app/points/apps'
    | '/_app/points/tenants'
    | '/_app/points/transactions'
    | '/_app/outreach/'
    | '/_app/auth/user/login-sim'
    | '/_app/auth/user/users'
    | '/_app/points/products/basic'
    | '/_app/points/products/bundles'
    | '/_app/points/products/categories'
    | '/_app/points/products/recharge'
    | '/_app/points/transactions/points-ledger'
    | '/_app/points/transactions/'
    | '/_app/points/transactions/recharge/new'
    | '/_app/points/transactions/recharge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/': {
      id: '/_app/outreach/'
      path: '/outreach'
      fullPath: '/outreach/'
      preLoaderRoute: typeof AppOutreachIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/transactions': {
      id: '/_app/points/transactions'
      path: '/points/transactions'
      fullPath: '/points/transactions'
      preLoaderRoute: typeof AppPointsTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/tenants': {
      id: '/_app/points/tenants'
      path: '/points/tenants'
      fullPath: '/points/tenants'
      preLoaderRoute: typeof AppPointsTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/apps': {
      id: '/_app/points/apps'
      path: '/points/apps'
      fullPath: '/points/apps'
      preLoaderRoute: typeof AppPointsAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/user': {
      id: '/_app/auth/user'
      path: '/auth/user'
      fullPath: '/auth/user'
      preLoaderRoute: typeof AppAuthUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/transactions/': {
      id: '/_app/points/transactions/'
      path: '/'
      fullPath: '/points/transactions/'
      preLoaderRoute: typeof AppPointsTransactionsIndexRouteImport
      parentRoute: typeof AppPointsTransactionsRoute
    }
    '/_app/points/transactions/points-ledger': {
      id: '/_app/points/transactions/points-ledger'
      path: '/points-ledger'
      fullPath: '/points/transactions/points-ledger'
      preLoaderRoute: typeof AppPointsTransactionsPointsLedgerRouteImport
      parentRoute: typeof AppPointsTransactionsRoute
    }
    '/_app/points/products/recharge': {
      id: '/_app/points/products/recharge'
      path: '/points/products/recharge'
      fullPath: '/points/products/recharge'
      preLoaderRoute: typeof AppPointsProductsRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/products/categories': {
      id: '/_app/points/products/categories'
      path: '/points/products/categories'
      fullPath: '/points/products/categories'
      preLoaderRoute: typeof AppPointsProductsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/products/bundles': {
      id: '/_app/points/products/bundles'
      path: '/points/products/bundles'
      fullPath: '/points/products/bundles'
      preLoaderRoute: typeof AppPointsProductsBundlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/products/basic': {
      id: '/_app/points/products/basic'
      path: '/points/products/basic'
      fullPath: '/points/products/basic'
      preLoaderRoute: typeof AppPointsProductsBasicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/user/users': {
      id: '/_app/auth/user/users'
      path: '/users'
      fullPath: '/auth/user/users'
      preLoaderRoute: typeof AppAuthUserUsersRouteImport
      parentRoute: typeof AppAuthUserRoute
    }
    '/_app/auth/user/login-sim': {
      id: '/_app/auth/user/login-sim'
      path: '/login-sim'
      fullPath: '/auth/user/login-sim'
      preLoaderRoute: typeof AppAuthUserLoginSimRouteImport
      parentRoute: typeof AppAuthUserRoute
    }
    '/_app/points/transactions/recharge/': {
      id: '/_app/points/transactions/recharge/'
      path: '/recharge'
      fullPath: '/points/transactions/recharge/'
      preLoaderRoute: typeof AppPointsTransactionsRechargeIndexRouteImport
      parentRoute: typeof AppPointsTransactionsRoute
    }
    '/_app/points/transactions/recharge/new': {
      id: '/_app/points/transactions/recharge/new'
      path: '/recharge/new'
      fullPath: '/points/transactions/recharge/new'
      preLoaderRoute: typeof AppPointsTransactionsRechargeNewRouteImport
      parentRoute: typeof AppPointsTransactionsRoute
    }
  }
}

interface AppAuthUserRouteChildren {
  AppAuthUserLoginSimRoute: typeof AppAuthUserLoginSimRoute
  AppAuthUserUsersRoute: typeof AppAuthUserUsersRoute
}

const AppAuthUserRouteChildren: AppAuthUserRouteChildren = {
  AppAuthUserLoginSimRoute: AppAuthUserLoginSimRoute,
  AppAuthUserUsersRoute: AppAuthUserUsersRoute,
}

const AppAuthUserRouteWithChildren = AppAuthUserRoute._addFileChildren(
  AppAuthUserRouteChildren,
)

interface AppPointsTransactionsRouteChildren {
  AppPointsTransactionsPointsLedgerRoute: typeof AppPointsTransactionsPointsLedgerRoute
  AppPointsTransactionsIndexRoute: typeof AppPointsTransactionsIndexRoute
  AppPointsTransactionsRechargeNewRoute: typeof AppPointsTransactionsRechargeNewRoute
  AppPointsTransactionsRechargeIndexRoute: typeof AppPointsTransactionsRechargeIndexRoute
}

const AppPointsTransactionsRouteChildren: AppPointsTransactionsRouteChildren = {
  AppPointsTransactionsPointsLedgerRoute:
    AppPointsTransactionsPointsLedgerRoute,
  AppPointsTransactionsIndexRoute: AppPointsTransactionsIndexRoute,
  AppPointsTransactionsRechargeNewRoute: AppPointsTransactionsRechargeNewRoute,
  AppPointsTransactionsRechargeIndexRoute:
    AppPointsTransactionsRechargeIndexRoute,
}

const AppPointsTransactionsRouteWithChildren =
  AppPointsTransactionsRoute._addFileChildren(
    AppPointsTransactionsRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAuthUserRoute: typeof AppAuthUserRouteWithChildren
  AppPointsAppsRoute: typeof AppPointsAppsRoute
  AppPointsTenantsRoute: typeof AppPointsTenantsRoute
  AppPointsTransactionsRoute: typeof AppPointsTransactionsRouteWithChildren
  AppOutreachIndexRoute: typeof AppOutreachIndexRoute
  AppPointsProductsBasicRoute: typeof AppPointsProductsBasicRoute
  AppPointsProductsBundlesRoute: typeof AppPointsProductsBundlesRoute
  AppPointsProductsCategoriesRoute: typeof AppPointsProductsCategoriesRoute
  AppPointsProductsRechargeRoute: typeof AppPointsProductsRechargeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAuthUserRoute: AppAuthUserRouteWithChildren,
  AppPointsAppsRoute: AppPointsAppsRoute,
  AppPointsTenantsRoute: AppPointsTenantsRoute,
  AppPointsTransactionsRoute: AppPointsTransactionsRouteWithChildren,
  AppOutreachIndexRoute: AppOutreachIndexRoute,
  AppPointsProductsBasicRoute: AppPointsProductsBasicRoute,
  AppPointsProductsBundlesRoute: AppPointsProductsBundlesRoute,
  AppPointsProductsCategoriesRoute: AppPointsProductsCategoriesRoute,
  AppPointsProductsRechargeRoute: AppPointsProductsRechargeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
