/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppOutreachIndexRouteImport } from './routes/_app.outreach.index'
import { Route as AppPointsTenantsRouteImport } from './routes/_app.points.tenants'
import { Route as AppPointsAppsRouteImport } from './routes/_app.points.apps'
import { Route as AppOutreachUsersRouteImport } from './routes/_app.outreach.users'
import { Route as AppOutreachRechargeRouteImport } from './routes/_app.outreach.recharge'
import { Route as AppOutreachReachEmptyRouteImport } from './routes/_app.outreach.reach-empty'
import { Route as AppOutreachReachRouteImport } from './routes/_app.outreach.reach'
import { Route as AppOutreachLeadsRouteImport } from './routes/_app.outreach.leads'
import { Route as AppOutreachInvoicesRouteImport } from './routes/_app.outreach.invoices'
import { Route as AppOutreachFootprintsEmptyRouteImport } from './routes/_app.outreach.footprints-empty'
import { Route as AppOutreachFootprintsRouteImport } from './routes/_app.outreach.footprints'
import { Route as AppOutreachFavoritesEmptyRouteImport } from './routes/_app.outreach.favorites-empty'
import { Route as AppOutreachFavoritesRouteImport } from './routes/_app.outreach.favorites'
import { Route as AppOutreachEnterpriseRouteImport } from './routes/_app.outreach.enterprise'
import { Route as AppOutreachBillsRouteImport } from './routes/_app.outreach.bills'
import { Route as AppOutreachBillingEmptyRouteImport } from './routes/_app.outreach.billing-empty'
import { Route as AppOutreachBillingRouteImport } from './routes/_app.outreach.billing'
import { Route as AppOutreachProductsIndexRouteImport } from './routes/_app.outreach.products.index'
import { Route as AppOutreachEnterpriseIndexRouteImport } from './routes/_app.outreach.enterprise.index'
import { Route as AppPointsProductsRechargeRouteImport } from './routes/_app.points.products.recharge'
import { Route as AppPointsProductsCategoriesRouteImport } from './routes/_app.points.products.categories'
import { Route as AppPointsProductsBundlesRouteImport } from './routes/_app.points.products.bundles'
import { Route as AppPointsProductsBasicRouteImport } from './routes/_app.points.products.basic'
import { Route as AppOutreachProductsHsRouteImport } from './routes/_app.outreach.products.$hs'
import { Route as AppOutreachEnterpriseIdRouteImport } from './routes/_app.outreach.enterprise.$id'
import { Route as AppOutreachEnterpriseIdIndexRouteImport } from './routes/_app.outreach.enterprise.$id.index'
import { Route as AppOutreachEnterpriseIdContactIdxRouteImport } from './routes/_app.outreach.enterprise.$id.contact.$idx'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachIndexRoute = AppOutreachIndexRouteImport.update({
  id: '/outreach/',
  path: '/outreach/',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsTenantsRoute = AppPointsTenantsRouteImport.update({
  id: '/points/tenants',
  path: '/points/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppPointsAppsRoute = AppPointsAppsRouteImport.update({
  id: '/points/apps',
  path: '/points/apps',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachUsersRoute = AppOutreachUsersRouteImport.update({
  id: '/outreach/users',
  path: '/outreach/users',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRechargeRoute = AppOutreachRechargeRouteImport.update({
  id: '/outreach/recharge',
  path: '/outreach/recharge',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachReachEmptyRoute = AppOutreachReachEmptyRouteImport.update({
  id: '/outreach/reach-empty',
  path: '/outreach/reach-empty',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachReachRoute = AppOutreachReachRouteImport.update({
  id: '/outreach/reach',
  path: '/outreach/reach',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachLeadsRoute = AppOutreachLeadsRouteImport.update({
  id: '/outreach/leads',
  path: '/outreach/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachInvoicesRoute = AppOutreachInvoicesRouteImport.update({
  id: '/outreach/invoices',
  path: '/outreach/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachFootprintsEmptyRoute =
  AppOutreachFootprintsEmptyRouteImport.update({
    id: '/outreach/footprints-empty',
    path: '/outreach/footprints-empty',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachFootprintsRoute = AppOutreachFootprintsRouteImport.update({
  id: '/outreach/footprints',
  path: '/outreach/footprints',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachFavoritesEmptyRoute =
  AppOutreachFavoritesEmptyRouteImport.update({
    id: '/outreach/favorites-empty',
    path: '/outreach/favorites-empty',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachFavoritesRoute = AppOutreachFavoritesRouteImport.update({
  id: '/outreach/favorites',
  path: '/outreach/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachEnterpriseRoute = AppOutreachEnterpriseRouteImport.update({
  id: '/outreach/enterprise',
  path: '/outreach/enterprise',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachBillsRoute = AppOutreachBillsRouteImport.update({
  id: '/outreach/bills',
  path: '/outreach/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachBillingEmptyRoute = AppOutreachBillingEmptyRouteImport.update({
  id: '/outreach/billing-empty',
  path: '/outreach/billing-empty',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachBillingRoute = AppOutreachBillingRouteImport.update({
  id: '/outreach/billing',
  path: '/outreach/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachProductsIndexRoute =
  AppOutreachProductsIndexRouteImport.update({
    id: '/outreach/products/',
    path: '/outreach/products/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOutreachEnterpriseIndexRoute =
  AppOutreachEnterpriseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOutreachEnterpriseRoute,
  } as any)
const AppPointsProductsRechargeRoute =
  AppPointsProductsRechargeRouteImport.update({
    id: '/points/products/recharge',
    path: '/points/products/recharge',
    getParentRoute: () => AppRoute,
  } as any)
const AppPointsProductsCategoriesRoute =
  AppPointsProductsCategoriesRouteImport.update({
    id: '/points/products/categories',
    path: '/points/products/categories',
    getParentRoute: () => AppRoute,
  } as any)
const AppPointsProductsBundlesRoute =
  AppPointsProductsBundlesRouteImport.update({
    id: '/points/products/bundles',
    path: '/points/products/bundles',
    getParentRoute: () => AppRoute,
  } as any)
const AppPointsProductsBasicRoute = AppPointsProductsBasicRouteImport.update({
  id: '/points/products/basic',
  path: '/points/products/basic',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachProductsHsRoute = AppOutreachProductsHsRouteImport.update({
  id: '/outreach/products/$hs',
  path: '/outreach/products/$hs',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachEnterpriseIdRoute = AppOutreachEnterpriseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOutreachEnterpriseRoute,
} as any)
const AppOutreachEnterpriseIdIndexRoute =
  AppOutreachEnterpriseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOutreachEnterpriseIdRoute,
  } as any)
const AppOutreachEnterpriseIdContactIdxRoute =
  AppOutreachEnterpriseIdContactIdxRouteImport.update({
    id: '/contact/$idx',
    path: '/contact/$idx',
    getParentRoute: () => AppOutreachEnterpriseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/outreach/billing': typeof AppOutreachBillingRoute
  '/outreach/billing-empty': typeof AppOutreachBillingEmptyRoute
  '/outreach/bills': typeof AppOutreachBillsRoute
  '/outreach/enterprise': typeof AppOutreachEnterpriseRouteWithChildren
  '/outreach/favorites': typeof AppOutreachFavoritesRoute
  '/outreach/favorites-empty': typeof AppOutreachFavoritesEmptyRoute
  '/outreach/footprints': typeof AppOutreachFootprintsRoute
  '/outreach/footprints-empty': typeof AppOutreachFootprintsEmptyRoute
  '/outreach/invoices': typeof AppOutreachInvoicesRoute
  '/outreach/leads': typeof AppOutreachLeadsRoute
  '/outreach/reach': typeof AppOutreachReachRoute
  '/outreach/reach-empty': typeof AppOutreachReachEmptyRoute
  '/outreach/recharge': typeof AppOutreachRechargeRoute
  '/outreach/users': typeof AppOutreachUsersRoute
  '/points/apps': typeof AppPointsAppsRoute
  '/points/tenants': typeof AppPointsTenantsRoute
  '/outreach/': typeof AppOutreachIndexRoute
  '/outreach/enterprise/$id': typeof AppOutreachEnterpriseIdRouteWithChildren
  '/outreach/products/$hs': typeof AppOutreachProductsHsRoute
  '/points/products/basic': typeof AppPointsProductsBasicRoute
  '/points/products/bundles': typeof AppPointsProductsBundlesRoute
  '/points/products/categories': typeof AppPointsProductsCategoriesRoute
  '/points/products/recharge': typeof AppPointsProductsRechargeRoute
  '/outreach/enterprise/': typeof AppOutreachEnterpriseIndexRoute
  '/outreach/products/': typeof AppOutreachProductsIndexRoute
  '/outreach/enterprise/$id/': typeof AppOutreachEnterpriseIdIndexRoute
  '/outreach/enterprise/$id/contact/$idx': typeof AppOutreachEnterpriseIdContactIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/outreach/billing': typeof AppOutreachBillingRoute
  '/outreach/billing-empty': typeof AppOutreachBillingEmptyRoute
  '/outreach/bills': typeof AppOutreachBillsRoute
  '/outreach/favorites': typeof AppOutreachFavoritesRoute
  '/outreach/favorites-empty': typeof AppOutreachFavoritesEmptyRoute
  '/outreach/footprints': typeof AppOutreachFootprintsRoute
  '/outreach/footprints-empty': typeof AppOutreachFootprintsEmptyRoute
  '/outreach/invoices': typeof AppOutreachInvoicesRoute
  '/outreach/leads': typeof AppOutreachLeadsRoute
  '/outreach/reach': typeof AppOutreachReachRoute
  '/outreach/reach-empty': typeof AppOutreachReachEmptyRoute
  '/outreach/recharge': typeof AppOutreachRechargeRoute
  '/outreach/users': typeof AppOutreachUsersRoute
  '/points/apps': typeof AppPointsAppsRoute
  '/points/tenants': typeof AppPointsTenantsRoute
  '/outreach': typeof AppOutreachIndexRoute
  '/outreach/products/$hs': typeof AppOutreachProductsHsRoute
  '/points/products/basic': typeof AppPointsProductsBasicRoute
  '/points/products/bundles': typeof AppPointsProductsBundlesRoute
  '/points/products/categories': typeof AppPointsProductsCategoriesRoute
  '/points/products/recharge': typeof AppPointsProductsRechargeRoute
  '/outreach/enterprise': typeof AppOutreachEnterpriseIndexRoute
  '/outreach/products': typeof AppOutreachProductsIndexRoute
  '/outreach/enterprise/$id': typeof AppOutreachEnterpriseIdIndexRoute
  '/outreach/enterprise/$id/contact/$idx': typeof AppOutreachEnterpriseIdContactIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/outreach/billing': typeof AppOutreachBillingRoute
  '/_app/outreach/billing-empty': typeof AppOutreachBillingEmptyRoute
  '/_app/outreach/bills': typeof AppOutreachBillsRoute
  '/_app/outreach/enterprise': typeof AppOutreachEnterpriseRouteWithChildren
  '/_app/outreach/favorites': typeof AppOutreachFavoritesRoute
  '/_app/outreach/favorites-empty': typeof AppOutreachFavoritesEmptyRoute
  '/_app/outreach/footprints': typeof AppOutreachFootprintsRoute
  '/_app/outreach/footprints-empty': typeof AppOutreachFootprintsEmptyRoute
  '/_app/outreach/invoices': typeof AppOutreachInvoicesRoute
  '/_app/outreach/leads': typeof AppOutreachLeadsRoute
  '/_app/outreach/reach': typeof AppOutreachReachRoute
  '/_app/outreach/reach-empty': typeof AppOutreachReachEmptyRoute
  '/_app/outreach/recharge': typeof AppOutreachRechargeRoute
  '/_app/outreach/users': typeof AppOutreachUsersRoute
  '/_app/points/apps': typeof AppPointsAppsRoute
  '/_app/points/tenants': typeof AppPointsTenantsRoute
  '/_app/outreach/': typeof AppOutreachIndexRoute
  '/_app/outreach/enterprise/$id': typeof AppOutreachEnterpriseIdRouteWithChildren
  '/_app/outreach/products/$hs': typeof AppOutreachProductsHsRoute
  '/_app/points/products/basic': typeof AppPointsProductsBasicRoute
  '/_app/points/products/bundles': typeof AppPointsProductsBundlesRoute
  '/_app/points/products/categories': typeof AppPointsProductsCategoriesRoute
  '/_app/points/products/recharge': typeof AppPointsProductsRechargeRoute
  '/_app/outreach/enterprise/': typeof AppOutreachEnterpriseIndexRoute
  '/_app/outreach/products/': typeof AppOutreachProductsIndexRoute
  '/_app/outreach/enterprise/$id/': typeof AppOutreachEnterpriseIdIndexRoute
  '/_app/outreach/enterprise/$id/contact/$idx': typeof AppOutreachEnterpriseIdContactIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/outreach/billing'
    | '/outreach/billing-empty'
    | '/outreach/bills'
    | '/outreach/enterprise'
    | '/outreach/favorites'
    | '/outreach/favorites-empty'
    | '/outreach/footprints'
    | '/outreach/footprints-empty'
    | '/outreach/invoices'
    | '/outreach/leads'
    | '/outreach/reach'
    | '/outreach/reach-empty'
    | '/outreach/recharge'
    | '/outreach/users'
    | '/points/apps'
    | '/points/tenants'
    | '/outreach/'
    | '/outreach/enterprise/$id'
    | '/outreach/products/$hs'
    | '/points/products/basic'
    | '/points/products/bundles'
    | '/points/products/categories'
    | '/points/products/recharge'
    | '/outreach/enterprise/'
    | '/outreach/products/'
    | '/outreach/enterprise/$id/'
    | '/outreach/enterprise/$id/contact/$idx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/outreach/billing'
    | '/outreach/billing-empty'
    | '/outreach/bills'
    | '/outreach/favorites'
    | '/outreach/favorites-empty'
    | '/outreach/footprints'
    | '/outreach/footprints-empty'
    | '/outreach/invoices'
    | '/outreach/leads'
    | '/outreach/reach'
    | '/outreach/reach-empty'
    | '/outreach/recharge'
    | '/outreach/users'
    | '/points/apps'
    | '/points/tenants'
    | '/outreach'
    | '/outreach/products/$hs'
    | '/points/products/basic'
    | '/points/products/bundles'
    | '/points/products/categories'
    | '/points/products/recharge'
    | '/outreach/enterprise'
    | '/outreach/products'
    | '/outreach/enterprise/$id'
    | '/outreach/enterprise/$id/contact/$idx'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/outreach/billing'
    | '/_app/outreach/billing-empty'
    | '/_app/outreach/bills'
    | '/_app/outreach/enterprise'
    | '/_app/outreach/favorites'
    | '/_app/outreach/favorites-empty'
    | '/_app/outreach/footprints'
    | '/_app/outreach/footprints-empty'
    | '/_app/outreach/invoices'
    | '/_app/outreach/leads'
    | '/_app/outreach/reach'
    | '/_app/outreach/reach-empty'
    | '/_app/outreach/recharge'
    | '/_app/outreach/users'
    | '/_app/points/apps'
    | '/_app/points/tenants'
    | '/_app/outreach/'
    | '/_app/outreach/enterprise/$id'
    | '/_app/outreach/products/$hs'
    | '/_app/points/products/basic'
    | '/_app/points/products/bundles'
    | '/_app/points/products/categories'
    | '/_app/points/products/recharge'
    | '/_app/outreach/enterprise/'
    | '/_app/outreach/products/'
    | '/_app/outreach/enterprise/$id/'
    | '/_app/outreach/enterprise/$id/contact/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/': {
      id: '/_app/outreach/'
      path: '/outreach'
      fullPath: '/outreach/'
      preLoaderRoute: typeof AppOutreachIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/tenants': {
      id: '/_app/points/tenants'
      path: '/points/tenants'
      fullPath: '/points/tenants'
      preLoaderRoute: typeof AppPointsTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/apps': {
      id: '/_app/points/apps'
      path: '/points/apps'
      fullPath: '/points/apps'
      preLoaderRoute: typeof AppPointsAppsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/users': {
      id: '/_app/outreach/users'
      path: '/outreach/users'
      fullPath: '/outreach/users'
      preLoaderRoute: typeof AppOutreachUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/recharge': {
      id: '/_app/outreach/recharge'
      path: '/outreach/recharge'
      fullPath: '/outreach/recharge'
      preLoaderRoute: typeof AppOutreachRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/reach-empty': {
      id: '/_app/outreach/reach-empty'
      path: '/outreach/reach-empty'
      fullPath: '/outreach/reach-empty'
      preLoaderRoute: typeof AppOutreachReachEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/reach': {
      id: '/_app/outreach/reach'
      path: '/outreach/reach'
      fullPath: '/outreach/reach'
      preLoaderRoute: typeof AppOutreachReachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/leads': {
      id: '/_app/outreach/leads'
      path: '/outreach/leads'
      fullPath: '/outreach/leads'
      preLoaderRoute: typeof AppOutreachLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/invoices': {
      id: '/_app/outreach/invoices'
      path: '/outreach/invoices'
      fullPath: '/outreach/invoices'
      preLoaderRoute: typeof AppOutreachInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/footprints-empty': {
      id: '/_app/outreach/footprints-empty'
      path: '/outreach/footprints-empty'
      fullPath: '/outreach/footprints-empty'
      preLoaderRoute: typeof AppOutreachFootprintsEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/footprints': {
      id: '/_app/outreach/footprints'
      path: '/outreach/footprints'
      fullPath: '/outreach/footprints'
      preLoaderRoute: typeof AppOutreachFootprintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/favorites-empty': {
      id: '/_app/outreach/favorites-empty'
      path: '/outreach/favorites-empty'
      fullPath: '/outreach/favorites-empty'
      preLoaderRoute: typeof AppOutreachFavoritesEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/favorites': {
      id: '/_app/outreach/favorites'
      path: '/outreach/favorites'
      fullPath: '/outreach/favorites'
      preLoaderRoute: typeof AppOutreachFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise': {
      id: '/_app/outreach/enterprise'
      path: '/outreach/enterprise'
      fullPath: '/outreach/enterprise'
      preLoaderRoute: typeof AppOutreachEnterpriseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/bills': {
      id: '/_app/outreach/bills'
      path: '/outreach/bills'
      fullPath: '/outreach/bills'
      preLoaderRoute: typeof AppOutreachBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/billing-empty': {
      id: '/_app/outreach/billing-empty'
      path: '/outreach/billing-empty'
      fullPath: '/outreach/billing-empty'
      preLoaderRoute: typeof AppOutreachBillingEmptyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/billing': {
      id: '/_app/outreach/billing'
      path: '/outreach/billing'
      fullPath: '/outreach/billing'
      preLoaderRoute: typeof AppOutreachBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/products/': {
      id: '/_app/outreach/products/'
      path: '/outreach/products'
      fullPath: '/outreach/products/'
      preLoaderRoute: typeof AppOutreachProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise/': {
      id: '/_app/outreach/enterprise/'
      path: '/'
      fullPath: '/outreach/enterprise/'
      preLoaderRoute: typeof AppOutreachEnterpriseIndexRouteImport
      parentRoute: typeof AppOutreachEnterpriseRoute
    }
    '/_app/points/products/recharge': {
      id: '/_app/points/products/recharge'
      path: '/points/products/recharge'
      fullPath: '/points/products/recharge'
      preLoaderRoute: typeof AppPointsProductsRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/products/categories': {
      id: '/_app/points/products/categories'
      path: '/points/products/categories'
      fullPath: '/points/products/categories'
      preLoaderRoute: typeof AppPointsProductsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/products/bundles': {
      id: '/_app/points/products/bundles'
      path: '/points/products/bundles'
      fullPath: '/points/products/bundles'
      preLoaderRoute: typeof AppPointsProductsBundlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/points/products/basic': {
      id: '/_app/points/products/basic'
      path: '/points/products/basic'
      fullPath: '/points/products/basic'
      preLoaderRoute: typeof AppPointsProductsBasicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/products/$hs': {
      id: '/_app/outreach/products/$hs'
      path: '/outreach/products/$hs'
      fullPath: '/outreach/products/$hs'
      preLoaderRoute: typeof AppOutreachProductsHsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outreach/enterprise/$id': {
      id: '/_app/outreach/enterprise/$id'
      path: '/$id'
      fullPath: '/outreach/enterprise/$id'
      preLoaderRoute: typeof AppOutreachEnterpriseIdRouteImport
      parentRoute: typeof AppOutreachEnterpriseRoute
    }
    '/_app/outreach/enterprise/$id/': {
      id: '/_app/outreach/enterprise/$id/'
      path: '/'
      fullPath: '/outreach/enterprise/$id/'
      preLoaderRoute: typeof AppOutreachEnterpriseIdIndexRouteImport
      parentRoute: typeof AppOutreachEnterpriseIdRoute
    }
    '/_app/outreach/enterprise/$id/contact/$idx': {
      id: '/_app/outreach/enterprise/$id/contact/$idx'
      path: '/contact/$idx'
      fullPath: '/outreach/enterprise/$id/contact/$idx'
      preLoaderRoute: typeof AppOutreachEnterpriseIdContactIdxRouteImport
      parentRoute: typeof AppOutreachEnterpriseIdRoute
    }
  }
}

interface AppOutreachEnterpriseIdRouteChildren {
  AppOutreachEnterpriseIdIndexRoute: typeof AppOutreachEnterpriseIdIndexRoute
  AppOutreachEnterpriseIdContactIdxRoute: typeof AppOutreachEnterpriseIdContactIdxRoute
}

const AppOutreachEnterpriseIdRouteChildren: AppOutreachEnterpriseIdRouteChildren =
  {
    AppOutreachEnterpriseIdIndexRoute: AppOutreachEnterpriseIdIndexRoute,
    AppOutreachEnterpriseIdContactIdxRoute:
      AppOutreachEnterpriseIdContactIdxRoute,
  }

const AppOutreachEnterpriseIdRouteWithChildren =
  AppOutreachEnterpriseIdRoute._addFileChildren(
    AppOutreachEnterpriseIdRouteChildren,
  )

interface AppOutreachEnterpriseRouteChildren {
  AppOutreachEnterpriseIdRoute: typeof AppOutreachEnterpriseIdRouteWithChildren
  AppOutreachEnterpriseIndexRoute: typeof AppOutreachEnterpriseIndexRoute
}

const AppOutreachEnterpriseRouteChildren: AppOutreachEnterpriseRouteChildren = {
  AppOutreachEnterpriseIdRoute: AppOutreachEnterpriseIdRouteWithChildren,
  AppOutreachEnterpriseIndexRoute: AppOutreachEnterpriseIndexRoute,
}

const AppOutreachEnterpriseRouteWithChildren =
  AppOutreachEnterpriseRoute._addFileChildren(
    AppOutreachEnterpriseRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOutreachBillingRoute: typeof AppOutreachBillingRoute
  AppOutreachBillingEmptyRoute: typeof AppOutreachBillingEmptyRoute
  AppOutreachBillsRoute: typeof AppOutreachBillsRoute
  AppOutreachEnterpriseRoute: typeof AppOutreachEnterpriseRouteWithChildren
  AppOutreachFavoritesRoute: typeof AppOutreachFavoritesRoute
  AppOutreachFavoritesEmptyRoute: typeof AppOutreachFavoritesEmptyRoute
  AppOutreachFootprintsRoute: typeof AppOutreachFootprintsRoute
  AppOutreachFootprintsEmptyRoute: typeof AppOutreachFootprintsEmptyRoute
  AppOutreachInvoicesRoute: typeof AppOutreachInvoicesRoute
  AppOutreachLeadsRoute: typeof AppOutreachLeadsRoute
  AppOutreachReachRoute: typeof AppOutreachReachRoute
  AppOutreachReachEmptyRoute: typeof AppOutreachReachEmptyRoute
  AppOutreachRechargeRoute: typeof AppOutreachRechargeRoute
  AppOutreachUsersRoute: typeof AppOutreachUsersRoute
  AppPointsAppsRoute: typeof AppPointsAppsRoute
  AppPointsTenantsRoute: typeof AppPointsTenantsRoute
  AppOutreachIndexRoute: typeof AppOutreachIndexRoute
  AppOutreachProductsHsRoute: typeof AppOutreachProductsHsRoute
  AppPointsProductsBasicRoute: typeof AppPointsProductsBasicRoute
  AppPointsProductsBundlesRoute: typeof AppPointsProductsBundlesRoute
  AppPointsProductsCategoriesRoute: typeof AppPointsProductsCategoriesRoute
  AppPointsProductsRechargeRoute: typeof AppPointsProductsRechargeRoute
  AppOutreachProductsIndexRoute: typeof AppOutreachProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOutreachBillingRoute: AppOutreachBillingRoute,
  AppOutreachBillingEmptyRoute: AppOutreachBillingEmptyRoute,
  AppOutreachBillsRoute: AppOutreachBillsRoute,
  AppOutreachEnterpriseRoute: AppOutreachEnterpriseRouteWithChildren,
  AppOutreachFavoritesRoute: AppOutreachFavoritesRoute,
  AppOutreachFavoritesEmptyRoute: AppOutreachFavoritesEmptyRoute,
  AppOutreachFootprintsRoute: AppOutreachFootprintsRoute,
  AppOutreachFootprintsEmptyRoute: AppOutreachFootprintsEmptyRoute,
  AppOutreachInvoicesRoute: AppOutreachInvoicesRoute,
  AppOutreachLeadsRoute: AppOutreachLeadsRoute,
  AppOutreachReachRoute: AppOutreachReachRoute,
  AppOutreachReachEmptyRoute: AppOutreachReachEmptyRoute,
  AppOutreachRechargeRoute: AppOutreachRechargeRoute,
  AppOutreachUsersRoute: AppOutreachUsersRoute,
  AppPointsAppsRoute: AppPointsAppsRoute,
  AppPointsTenantsRoute: AppPointsTenantsRoute,
  AppOutreachIndexRoute: AppOutreachIndexRoute,
  AppOutreachProductsHsRoute: AppOutreachProductsHsRoute,
  AppPointsProductsBasicRoute: AppPointsProductsBasicRoute,
  AppPointsProductsBundlesRoute: AppPointsProductsBundlesRoute,
  AppPointsProductsCategoriesRoute: AppPointsProductsCategoriesRoute,
  AppPointsProductsRechargeRoute: AppPointsProductsRechargeRoute,
  AppOutreachProductsIndexRoute: AppOutreachProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
